version: "3.9"

services: 
  redis:
    image: "redis:7-alpine"
    container_name: "yota-redis"
    volumes:
      - redis_data:/data
    ports:
      - "6378:6379"
    networks:
      - redis-network
    command: redis-server --appendonly yes

  postgres:
    image: "postgres:16"
    container_name: "yota-postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: yota_db

volumes:
  redis_data:
  postgres_data:

networks:
  redis-network:
    driver: bridge
